trigger:
  branches:
    include:
      - main

pool:
  name: Vk

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  buildArtifactName: 'my-webapp'

stages:
  - stage: Build
    displayName: 'Build Maven Project'
    jobs:
      - job: MavenBuild
        displayName: 'Build with Maven'
        steps:
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              path: $(MAVEN_CACHE_FOLDER)
              restoreKeys: |
                maven | "$(Agent.OS)"
            displayName: 'Restore Maven cache'

          - task: Maven@3
            displayName: 'Maven Build'
            inputs:
              mavenPomFile: 'my-webapps/pom.xml'
              goals: 'clean package'
              mavenOptions: '-Xmx1024m'
              javaHomeOption: 'JDK11'
              publishJUnitResults: false
              options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              PathtoPublish: 'my-webapps/target'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: PublishToAzureArtifacts
    displayName: 'Publish to Azure Artifacts'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: PushArtifact
        displayName: 'Push to Azure Artifacts Feed'
        steps:
          - task: MavenAuthenticate@0
            displayName: 'Authenticate to Azure Artifacts'
            inputs:
              artifactsFeeds: 'Project_4th_EVAL/java-artifacts'

          - task: Maven@3
            displayName: 'Maven Deploy'
            inputs:
              mavenPomFile: 'my-webapps/pom.xml'
              goals: 'deploy'
              mavenOptions: '-Xmx1024m'
              javaHomeOption: 'JDK11'
              options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
